import Link from "next/link";
import { Navbar } from "@/components/Navbar";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white">
      <Navbar />
      <main className="mx-auto max-w-2xl px-6 py-16 lg:py-24">
        <h1 className="text-3xl font-bold tracking-tight text-white">Terms of Service</h1>
        <p className="mt-2 text-sm text-zinc-500">Last updated: March 5, 2026</p>

        <div className="mt-10 space-y-8 text-sm leading-relaxed text-zinc-300">

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">1. Acceptance of Terms</h2>
            <p>By using SLAY Writer, you agree to these terms. If you don't agree, please don't use the service.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">2. Description of Service</h2>
            <p>SLAY Writer is an AI-powered LinkedIn post generator. We provide Free and Pro plans.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">3. Free Plan</h2>
            <ul className="ml-4 mt-1 list-disc space-y-1 text-zinc-400">
              <li>10 post generations per month</li>
              <li>No credit card required</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">4. Pro Plan</h2>
            <ul className="ml-4 mt-1 list-disc space-y-1 text-zinc-400">
              <li>$9/month after 7-day free trial</li>
              <li>Credit card required at signup</li>
              <li>Cancel anytime before trial ends to avoid charges</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">5. Payments &amp; Billing</h2>
            <ul className="ml-4 mt-1 list-disc space-y-1 text-zinc-400">
              <li>Payments are processed by Stripe</li>
              <li>You will be charged $9/month after your 7-day free trial ends</li>
              <li>All charges are in USD</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">6. Cancellation</h2>
            <ul className="ml-4 mt-1 list-disc space-y-1 text-zinc-400">
              <li>Cancel anytime via your account dashboard</li>
              <li>After cancellation, you keep Pro access until the end of your billing period</li>
              <li>No refunds for partial months</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">7. AI-Generated Content</h2>
            <ul className="ml-4 mt-1 list-disc space-y-1 text-zinc-400">
              <li>Content is generated by Claude AI (Anthropic)</li>
              <li>You own the content you generate</li>
              <li>We are not responsible for how you use generated content</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">8. Prohibited Use</h2>
            <p className="mb-2">You may not use SLAY Writer to generate:</p>
            <ul className="ml-4 list-disc space-y-1 text-zinc-400">
              <li>Spam or misleading content</li>
              <li>Content that violates LinkedIn's terms of service</li>
              <li>Harmful or illegal content</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">9. Limitation of Liability</h2>
            <p>SLAY Writer is provided "as is". We are not liable for any damages arising from use of the service.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">10. Changes to Terms</h2>
            <p>We may update these terms at any time. Continued use of the service means you accept the new terms.</p>
          </section>

          <section>
            <h2 className="mb-2 text-base font-semibold text-white">11. Contact</h2>
            <p>Questions? Email us at: <span className="text-amber-400">sochan567890@gmail.com</span></p>
          </section>

        </div>

        <div className="mt-12 border-t border-zinc-800 pt-8">
          <Link href="/" className="text-sm text-zinc-500 hover:text-white transition-colors">
            ← Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
